AWSTemplateFormatVersion: 2010-09-09
Description: Lab template

# DynamoDB Table

Resources:

##################
# DynamoDB Table #
##################

  InventoryDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Inventory
      AttributeDefinitions:
        - AttributeName: Store
          AttributeType: S
        - AttributeName: Item
          AttributeType: S
      KeySchema:
        - AttributeName: Store
          KeyType: HASH
        - AttributeName: Item
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES